### ISSUE TITLE
Proposal for a new merchant: `Isabella's Coffee`

### ISSUE THREAD

**Issue by Unbanked0** [Bank-Exit/bank_exit#14]
A new proposition for a merchant has been submitted. Please take a look and add it to OpenStreetMap if relevant:

```yaml
---
name: Isabella's Coffee
category: Café
other_category: ''
street: 1425 SE Bridge Road
postcode: '33455'
city: Hobe Sound
country: United States
phone: ''
website: https://isabellas.coffee/
description: " All of our coffee is certified organic, Fair Trade, and tested for
  mold and mycotoxins. \r\nWe offer whole or ground organic coffee beans. We also
  have a full espresso bar with homemade seasonal syrups. \r\nOur syrups use ONLY
  organic ingredients \r\n\r\nWe're at the Hobe Sound Farmer's market\r\n\r\nsaturday
  or sunday from 09:00 to 14:00\r\n\r\nCheck our instagram for scheduling"
coins:
- bitcoin
- monero
- lightning
- gold
- silver
ask_kyc: false
contact_facebook: ''
contact_twitter: ''
contact_telegram: ''
contact_signal: ''
contact_session: ''
contact_tripadvisor: ''
contact_matrix: ''
contact_jabber: ''
contact_youtube: ''
contact_linkedin: ''
contact_instagram: https://instagram.com/isabellas.coffee
contact_tiktok: ''
contact_odysee: ''
delivery: true
delivery_zone: World

```

---

*Note: this issue has been automatically opened from bank-exit website using the Github API.*
